/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as SignInRouteRouteImport } from './routes/sign-in/route'
import { Route as SignUpRouteRouteImport } from './routes/sign-up/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardNewRouteImport } from './routes/dashboard/new'
import { Route as GithubCallbackRouteImport } from './routes/github/callback'
import { Route as ProjectsProjectIdRouteRouteImport } from './routes/projects/$projectId/route'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up/$'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdConfigRouteImport } from './routes/projects/$projectId/config'
import { Route as ProjectsProjectIdEditRouteImport } from './routes/projects/$projectId/edit'
import { Route as ProjectsProjectIdDatabasesNewRouteImport } from './routes/projects/$projectId/databases/new'
import { Route as ProjectsProjectIdGithub_servicesNewRouteImport } from './routes/projects/$projectId/github_services/new'
import { Route as ProjectsProjectIdIntegrationsIndexRouteImport } from './routes/projects/$projectId/integrations/index'
import { Route as ProjectsProjectIdServicesNewRouteImport } from './routes/projects/$projectId/services/new'
import { Route as ProjectsProjectIdDatabasesDatabaseIdIndexRouteImport } from './routes/projects/$projectId/databases/$databaseId/index'
import { Route as ProjectsProjectIdDatabasesDatabaseIdEditRouteImport } from './routes/projects/$projectId/databases/$databaseId/edit'
import { Route as ProjectsProjectIdGithub_servicesGithubServiceIdIndexRouteImport } from './routes/projects/$projectId/github_services/$githubServiceId/index'
import { Route as ProjectsProjectIdGithub_servicesGithubServiceIdEditRouteImport } from './routes/projects/$projectId/github_services/$githubServiceId/edit'
import { Route as ProjectsProjectIdServicesServiceIdIndexRouteImport } from './routes/projects/$projectId/services/$serviceId/index'
import { Route as ProjectsProjectIdServicesServiceIdEditRouteImport } from './routes/projects/$projectId/services/$serviceId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRouteRoute = SignInRouteRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRouteRoute = SignUpRouteRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const GithubCallbackRoute = GithubCallbackRouteImport.update({
  id: '/github/callback',
  path: '/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRouteRoute = ProjectsProjectIdRouteRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignInRouteRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRouteRoute,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignUpRouteRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignUpRouteRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdConfigRoute = ProjectsProjectIdConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdEditRoute = ProjectsProjectIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdDatabasesNewRoute =
  ProjectsProjectIdDatabasesNewRouteImport.update({
    id: '/databases/new',
    path: '/databases/new',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdGithub_servicesNewRoute =
  ProjectsProjectIdGithub_servicesNewRouteImport.update({
    id: '/github_services/new',
    path: '/github_services/new',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdIntegrationsIndexRoute =
  ProjectsProjectIdIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdServicesNewRoute =
  ProjectsProjectIdServicesNewRouteImport.update({
    id: '/services/new',
    path: '/services/new',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdDatabasesDatabaseIdIndexRoute =
  ProjectsProjectIdDatabasesDatabaseIdIndexRouteImport.update({
    id: '/databases/$databaseId/',
    path: '/databases/$databaseId/',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdDatabasesDatabaseIdEditRoute =
  ProjectsProjectIdDatabasesDatabaseIdEditRouteImport.update({
    id: '/databases/$databaseId/edit',
    path: '/databases/$databaseId/edit',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdGithub_servicesGithubServiceIdIndexRoute =
  ProjectsProjectIdGithub_servicesGithubServiceIdIndexRouteImport.update({
    id: '/github_services/$githubServiceId/',
    path: '/github_services/$githubServiceId/',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdGithub_servicesGithubServiceIdEditRoute =
  ProjectsProjectIdGithub_servicesGithubServiceIdEditRouteImport.update({
    id: '/github_services/$githubServiceId/edit',
    path: '/github_services/$githubServiceId/edit',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdServicesServiceIdIndexRoute =
  ProjectsProjectIdServicesServiceIdIndexRouteImport.update({
    id: '/services/$serviceId/',
    path: '/services/$serviceId/',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdServicesServiceIdEditRoute =
  ProjectsProjectIdServicesServiceIdEditRouteImport.update({
    id: '/services/$serviceId/edit',
    path: '/services/$serviceId/edit',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/sign-in': typeof SignInRouteRouteWithChildren
  '/sign-up': typeof SignUpRouteRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/dashboard/new': typeof DashboardNewRoute
  '/github/callback': typeof GithubCallbackRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/projects/$projectId/config': typeof ProjectsProjectIdConfigRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/databases/new': typeof ProjectsProjectIdDatabasesNewRoute
  '/projects/$projectId/github_services/new': typeof ProjectsProjectIdGithub_servicesNewRoute
  '/projects/$projectId/services/new': typeof ProjectsProjectIdServicesNewRoute
  '/projects/$projectId/integrations/': typeof ProjectsProjectIdIntegrationsIndexRoute
  '/projects/$projectId/databases/$databaseId/edit': typeof ProjectsProjectIdDatabasesDatabaseIdEditRoute
  '/projects/$projectId/github_services/$githubServiceId/edit': typeof ProjectsProjectIdGithub_servicesGithubServiceIdEditRoute
  '/projects/$projectId/services/$serviceId/edit': typeof ProjectsProjectIdServicesServiceIdEditRoute
  '/projects/$projectId/databases/$databaseId/': typeof ProjectsProjectIdDatabasesDatabaseIdIndexRoute
  '/projects/$projectId/github_services/$githubServiceId/': typeof ProjectsProjectIdGithub_servicesGithubServiceIdIndexRoute
  '/projects/$projectId/services/$serviceId/': typeof ProjectsProjectIdServicesServiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/github/callback': typeof GithubCallbackRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard': typeof DashboardIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/projects/$projectId/config': typeof ProjectsProjectIdConfigRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/databases/new': typeof ProjectsProjectIdDatabasesNewRoute
  '/projects/$projectId/github_services/new': typeof ProjectsProjectIdGithub_servicesNewRoute
  '/projects/$projectId/services/new': typeof ProjectsProjectIdServicesNewRoute
  '/projects/$projectId/integrations': typeof ProjectsProjectIdIntegrationsIndexRoute
  '/projects/$projectId/databases/$databaseId/edit': typeof ProjectsProjectIdDatabasesDatabaseIdEditRoute
  '/projects/$projectId/github_services/$githubServiceId/edit': typeof ProjectsProjectIdGithub_servicesGithubServiceIdEditRoute
  '/projects/$projectId/services/$serviceId/edit': typeof ProjectsProjectIdServicesServiceIdEditRoute
  '/projects/$projectId/databases/$databaseId': typeof ProjectsProjectIdDatabasesDatabaseIdIndexRoute
  '/projects/$projectId/github_services/$githubServiceId': typeof ProjectsProjectIdGithub_servicesGithubServiceIdIndexRoute
  '/projects/$projectId/services/$serviceId': typeof ProjectsProjectIdServicesServiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/sign-in': typeof SignInRouteRouteWithChildren
  '/sign-up': typeof SignUpRouteRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/dashboard/new': typeof DashboardNewRoute
  '/github/callback': typeof GithubCallbackRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/projects/$projectId/config': typeof ProjectsProjectIdConfigRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/databases/new': typeof ProjectsProjectIdDatabasesNewRoute
  '/projects/$projectId/github_services/new': typeof ProjectsProjectIdGithub_servicesNewRoute
  '/projects/$projectId/services/new': typeof ProjectsProjectIdServicesNewRoute
  '/projects/$projectId/integrations/': typeof ProjectsProjectIdIntegrationsIndexRoute
  '/projects/$projectId/databases/$databaseId/edit': typeof ProjectsProjectIdDatabasesDatabaseIdEditRoute
  '/projects/$projectId/github_services/$githubServiceId/edit': typeof ProjectsProjectIdGithub_servicesGithubServiceIdEditRoute
  '/projects/$projectId/services/$serviceId/edit': typeof ProjectsProjectIdServicesServiceIdEditRoute
  '/projects/$projectId/databases/$databaseId/': typeof ProjectsProjectIdDatabasesDatabaseIdIndexRoute
  '/projects/$projectId/github_services/$githubServiceId/': typeof ProjectsProjectIdGithub_servicesGithubServiceIdIndexRoute
  '/projects/$projectId/services/$serviceId/': typeof ProjectsProjectIdServicesServiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/projects/$projectId'
    | '/dashboard/new'
    | '/github/callback'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/'
    | '/sign-in/'
    | '/sign-up/'
    | '/projects/$projectId/config'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/'
    | '/projects/$projectId/databases/new'
    | '/projects/$projectId/github_services/new'
    | '/projects/$projectId/services/new'
    | '/projects/$projectId/integrations/'
    | '/projects/$projectId/databases/$databaseId/edit'
    | '/projects/$projectId/github_services/$githubServiceId/edit'
    | '/projects/$projectId/services/$serviceId/edit'
    | '/projects/$projectId/databases/$databaseId/'
    | '/projects/$projectId/github_services/$githubServiceId/'
    | '/projects/$projectId/services/$serviceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/new'
    | '/github/callback'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/projects/$projectId/config'
    | '/projects/$projectId/edit'
    | '/projects/$projectId'
    | '/projects/$projectId/databases/new'
    | '/projects/$projectId/github_services/new'
    | '/projects/$projectId/services/new'
    | '/projects/$projectId/integrations'
    | '/projects/$projectId/databases/$databaseId/edit'
    | '/projects/$projectId/github_services/$githubServiceId/edit'
    | '/projects/$projectId/services/$serviceId/edit'
    | '/projects/$projectId/databases/$databaseId'
    | '/projects/$projectId/github_services/$githubServiceId'
    | '/projects/$projectId/services/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/projects/$projectId'
    | '/dashboard/new'
    | '/github/callback'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/'
    | '/sign-in/'
    | '/sign-up/'
    | '/projects/$projectId/config'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/'
    | '/projects/$projectId/databases/new'
    | '/projects/$projectId/github_services/new'
    | '/projects/$projectId/services/new'
    | '/projects/$projectId/integrations/'
    | '/projects/$projectId/databases/$databaseId/edit'
    | '/projects/$projectId/github_services/$githubServiceId/edit'
    | '/projects/$projectId/services/$serviceId/edit'
    | '/projects/$projectId/databases/$databaseId/'
    | '/projects/$projectId/github_services/$githubServiceId/'
    | '/projects/$projectId/services/$serviceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SignInRouteRoute: typeof SignInRouteRouteWithChildren
  SignUpRouteRoute: typeof SignUpRouteRouteWithChildren
  ProjectsProjectIdRouteRoute: typeof ProjectsProjectIdRouteRouteWithChildren
  GithubCallbackRoute: typeof GithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/github/callback': {
      id: '/github/callback'
      path: '/github/callback'
      fullPath: '/github/callback'
      preLoaderRoute: typeof GithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof SignInRouteRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof SignInRouteRoute
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof SignUpRouteRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof SignUpRouteRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/config': {
      id: '/projects/$projectId/config'
      path: '/config'
      fullPath: '/projects/$projectId/config'
      preLoaderRoute: typeof ProjectsProjectIdConfigRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/edit': {
      id: '/projects/$projectId/edit'
      path: '/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof ProjectsProjectIdEditRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/databases/new': {
      id: '/projects/$projectId/databases/new'
      path: '/databases/new'
      fullPath: '/projects/$projectId/databases/new'
      preLoaderRoute: typeof ProjectsProjectIdDatabasesNewRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/github_services/new': {
      id: '/projects/$projectId/github_services/new'
      path: '/github_services/new'
      fullPath: '/projects/$projectId/github_services/new'
      preLoaderRoute: typeof ProjectsProjectIdGithub_servicesNewRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/integrations/': {
      id: '/projects/$projectId/integrations/'
      path: '/integrations'
      fullPath: '/projects/$projectId/integrations/'
      preLoaderRoute: typeof ProjectsProjectIdIntegrationsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/services/new': {
      id: '/projects/$projectId/services/new'
      path: '/services/new'
      fullPath: '/projects/$projectId/services/new'
      preLoaderRoute: typeof ProjectsProjectIdServicesNewRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/databases/$databaseId/': {
      id: '/projects/$projectId/databases/$databaseId/'
      path: '/databases/$databaseId'
      fullPath: '/projects/$projectId/databases/$databaseId/'
      preLoaderRoute: typeof ProjectsProjectIdDatabasesDatabaseIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/databases/$databaseId/edit': {
      id: '/projects/$projectId/databases/$databaseId/edit'
      path: '/databases/$databaseId/edit'
      fullPath: '/projects/$projectId/databases/$databaseId/edit'
      preLoaderRoute: typeof ProjectsProjectIdDatabasesDatabaseIdEditRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/github_services/$githubServiceId/': {
      id: '/projects/$projectId/github_services/$githubServiceId/'
      path: '/github_services/$githubServiceId'
      fullPath: '/projects/$projectId/github_services/$githubServiceId/'
      preLoaderRoute: typeof ProjectsProjectIdGithub_servicesGithubServiceIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/github_services/$githubServiceId/edit': {
      id: '/projects/$projectId/github_services/$githubServiceId/edit'
      path: '/github_services/$githubServiceId/edit'
      fullPath: '/projects/$projectId/github_services/$githubServiceId/edit'
      preLoaderRoute: typeof ProjectsProjectIdGithub_servicesGithubServiceIdEditRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/services/$serviceId/': {
      id: '/projects/$projectId/services/$serviceId/'
      path: '/services/$serviceId'
      fullPath: '/projects/$projectId/services/$serviceId/'
      preLoaderRoute: typeof ProjectsProjectIdServicesServiceIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/services/$serviceId/edit': {
      id: '/projects/$projectId/services/$serviceId/edit'
      path: '/services/$serviceId/edit'
      fullPath: '/projects/$projectId/services/$serviceId/edit'
      preLoaderRoute: typeof ProjectsProjectIdServicesServiceIdEditRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardNewRoute: typeof DashboardNewRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardNewRoute: DashboardNewRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface SignInRouteRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
  SignInIndexRoute: typeof SignInIndexRoute
}

const SignInRouteRouteChildren: SignInRouteRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
  SignInIndexRoute: SignInIndexRoute,
}

const SignInRouteRouteWithChildren = SignInRouteRoute._addFileChildren(
  SignInRouteRouteChildren,
)

interface SignUpRouteRouteChildren {
  SignUpSplatRoute: typeof SignUpSplatRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
}

const SignUpRouteRouteChildren: SignUpRouteRouteChildren = {
  SignUpSplatRoute: SignUpSplatRoute,
  SignUpIndexRoute: SignUpIndexRoute,
}

const SignUpRouteRouteWithChildren = SignUpRouteRoute._addFileChildren(
  SignUpRouteRouteChildren,
)

interface ProjectsProjectIdRouteRouteChildren {
  ProjectsProjectIdConfigRoute: typeof ProjectsProjectIdConfigRoute
  ProjectsProjectIdEditRoute: typeof ProjectsProjectIdEditRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdDatabasesNewRoute: typeof ProjectsProjectIdDatabasesNewRoute
  ProjectsProjectIdGithub_servicesNewRoute: typeof ProjectsProjectIdGithub_servicesNewRoute
  ProjectsProjectIdServicesNewRoute: typeof ProjectsProjectIdServicesNewRoute
  ProjectsProjectIdIntegrationsIndexRoute: typeof ProjectsProjectIdIntegrationsIndexRoute
  ProjectsProjectIdDatabasesDatabaseIdEditRoute: typeof ProjectsProjectIdDatabasesDatabaseIdEditRoute
  ProjectsProjectIdGithub_servicesGithubServiceIdEditRoute: typeof ProjectsProjectIdGithub_servicesGithubServiceIdEditRoute
  ProjectsProjectIdServicesServiceIdEditRoute: typeof ProjectsProjectIdServicesServiceIdEditRoute
  ProjectsProjectIdDatabasesDatabaseIdIndexRoute: typeof ProjectsProjectIdDatabasesDatabaseIdIndexRoute
  ProjectsProjectIdGithub_servicesGithubServiceIdIndexRoute: typeof ProjectsProjectIdGithub_servicesGithubServiceIdIndexRoute
  ProjectsProjectIdServicesServiceIdIndexRoute: typeof ProjectsProjectIdServicesServiceIdIndexRoute
}

const ProjectsProjectIdRouteRouteChildren: ProjectsProjectIdRouteRouteChildren =
  {
    ProjectsProjectIdConfigRoute: ProjectsProjectIdConfigRoute,
    ProjectsProjectIdEditRoute: ProjectsProjectIdEditRoute,
    ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
    ProjectsProjectIdDatabasesNewRoute: ProjectsProjectIdDatabasesNewRoute,
    ProjectsProjectIdGithub_servicesNewRoute:
      ProjectsProjectIdGithub_servicesNewRoute,
    ProjectsProjectIdServicesNewRoute: ProjectsProjectIdServicesNewRoute,
    ProjectsProjectIdIntegrationsIndexRoute:
      ProjectsProjectIdIntegrationsIndexRoute,
    ProjectsProjectIdDatabasesDatabaseIdEditRoute:
      ProjectsProjectIdDatabasesDatabaseIdEditRoute,
    ProjectsProjectIdGithub_servicesGithubServiceIdEditRoute:
      ProjectsProjectIdGithub_servicesGithubServiceIdEditRoute,
    ProjectsProjectIdServicesServiceIdEditRoute:
      ProjectsProjectIdServicesServiceIdEditRoute,
    ProjectsProjectIdDatabasesDatabaseIdIndexRoute:
      ProjectsProjectIdDatabasesDatabaseIdIndexRoute,
    ProjectsProjectIdGithub_servicesGithubServiceIdIndexRoute:
      ProjectsProjectIdGithub_servicesGithubServiceIdIndexRoute,
    ProjectsProjectIdServicesServiceIdIndexRoute:
      ProjectsProjectIdServicesServiceIdIndexRoute,
  }

const ProjectsProjectIdRouteRouteWithChildren =
  ProjectsProjectIdRouteRoute._addFileChildren(
    ProjectsProjectIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SignInRouteRoute: SignInRouteRouteWithChildren,
  SignUpRouteRoute: SignUpRouteRouteWithChildren,
  ProjectsProjectIdRouteRoute: ProjectsProjectIdRouteRouteWithChildren,
  GithubCallbackRoute: GithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
